// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkLX0lCcsI88T_QYcMsmosjC_9k9ptlUU',
    appId: '1:128652730107:web:1ce71044ac702035689a5e',
    messagingSenderId: '128652730107',
    projectId: 'flutter-projects-dd117',
    authDomain: 'flutter-projects-dd117.firebaseapp.com',
    storageBucket: 'flutter-projects-dd117.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMo0MiFFzQerDb_yoKvce26PKwZMe3bSI',
    appId: '1:128652730107:android:82894cdf0f578450689a5e',
    messagingSenderId: '128652730107',
    projectId: 'flutter-projects-dd117',
    storageBucket: 'flutter-projects-dd117.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXOJHYorfBgZUv72Pefl_x41ElvdcAOIo',
    appId: '1:128652730107:ios:53cc40149f65762b689a5e',
    messagingSenderId: '128652730107',
    projectId: 'flutter-projects-dd117',
    storageBucket: 'flutter-projects-dd117.firebasestorage.app',
    iosBundleId: 'com.example.pushNotificationsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXOJHYorfBgZUv72Pefl_x41ElvdcAOIo',
    appId: '1:128652730107:ios:53cc40149f65762b689a5e',
    messagingSenderId: '128652730107',
    projectId: 'flutter-projects-dd117',
    storageBucket: 'flutter-projects-dd117.firebasestorage.app',
    iosBundleId: 'com.example.pushNotificationsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkLX0lCcsI88T_QYcMsmosjC_9k9ptlUU',
    appId: '1:128652730107:web:47315d0cd5de5c15689a5e',
    messagingSenderId: '128652730107',
    projectId: 'flutter-projects-dd117',
    authDomain: 'flutter-projects-dd117.firebaseapp.com',
    storageBucket: 'flutter-projects-dd117.firebasestorage.app',
  );
}
